CREATE DATABASE API;

USE API;

CREATE TABLE TB_PESSOAS(
	IDPESSOA INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	EMAIL VARCHAR(30),
	SENHA VARCHAR(100),
	CPF VARCHAR(11),
	TELEFONE VARCHAR(30),
	ENDERECO VARCHAR(100)
)DEFAULT CHARSET = UTF8;

CREATE TABLE TB_GRUPOS(
	IDGRUPO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	TEMA VARCHAR(30),
	DESCRICAO VARCHAR(100)
)DEFAULT CHARSET = UTF8;

CREATE TABLE TB_PESSOA_GRUPO(
	ID_PG INT PRIMARY KEY AUTO_INCREMENT,
	ID_GRUPO INT,
	ID_PESSOA INT
)DEFAULT CHARSET = UTF8;

ALTER TABLE TB_PESSOA_GRUPO ADD CONSTRAINT FK_GRUPO
FOREIGN KEY(ID_GRUPO) REFERENCES TB_GRUPOS(IDGRUPO);

ALTER TABLE TB_PESSOA_GRUPO ADD CONSTRAINT FK_PESSOA
FOREIGN KEY(ID_PESSOA) REFERENCES TB_PESSOAS(IDPESSOA);